default:
  before_script:
    - python --version
    - pip --version

stages:
  - format
  - lint
  - type_check
  - test
  - coverage

format:
  stage: format
  script:
    - pip install -r requirements-dev.txt
    - python -m ruff format .
  cache:
    paths:
      - .ruff_cache/
  artifacts:
    when: always
    expire_in: 1h
    

lint:
  stage: lint
  script:
    - pip install -r requirements-dev.txt
    - python -m ruff check .

type_check:
  stage: type_check
  script:
    - pip install -r requirements-dev.txt
    - python -m mypy backend --ignore-missing-imports

test:
  stage: test
  script:
    - pip install -r requirements-dev.txt
    - pytest tests

coverage:
  stage: coverage
  script:
    - pip install -r requirements-dev.txt
    - pytest tests --cov=. --cov-report=xml --cov-report=term-missing