format:
  stage: format
  script:
    - pip install -r requirements-dev.txt
    - python -m ruff format .
    - python -m ruff check .

lint:
  stage: lint
  script:
    - pip install -r requirements-dev.txt
    - python -m ruff check .

type_check:
  stage: type_check
  script:
    - pip install -r requirements-dev.txt
    - python -m mypy backend --ignore-missing-imports

test:
  stage: test
  script:
    - pip install -r requirements-dev.txt
    - pytest tests

coverage:
  stage: coverage
  script:
    - pip install -r requirements-dev.txt
    - pytest tests --cov=. --cov-report=xml --cov-report=term-missing