variables:
  RUFF_CACHE_DIR: ".ruff_cache_disabled"

default:
  before_script:
    - python --version
    - pip --version
    - python -m pip install --upgrade pip
    - pip install -r requirements-dev.txt


stages:
  - format
  - lint
  - type_check
  - test
  - coverage

format:
  stage: format
  script:
   - python -m ruff format --check .
    
  
lint:
  stage: lint
  script:
    - pip install -r requirements-dev.txt
    - python -m ruff check .

type_check:
  stage: type_check
  script:
    - python -m mypy backend --ignore-missing-imports
  
test:
  stage: test
  script:
    - python -m pytest tests
  

coverage:
  stage: coverage
  script:
    - python -m pytest tests --cov=. --cov-report=xml --cov-report=term-missing
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - coverage.xml